<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T003_kelas_model extends CI_Model
{

    public $table = 't003_kelas';
    public $id = 'idkelas'; public $orderBy = "kelas";
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        // $this->db->order_by($this->id, $this->order);
        $this->db->order_by($this->orderBy, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select("idkelas, kelas, t003_kelas.idguru, namaguru");
        $this->db->from("t003_kelas");
        $this->db->join("t002_guru", "t003_kelas.idguru = t002_guru.idguru");
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idkelas', $q);
      	$this->db->or_like('kelas', $q);
      	$this->db->or_like('idguru', $q);
      	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idkelas', $q);
      	$this->db->or_like('kelas', $q);
      	$this->db->or_like('t003_kelas.idguru', $q);
      	$this->db->limit($limit, $start);
        // tambahan
        $this->db->select("idkelas, kelas, t003_kelas.idguru, namaguru");
        $this->db->from("t003_kelas");
        $this->db->join("t002_guru", "t003_kelas.idguru = t002_guru.idguru");
        //return $this->db->get($this->table)->result();
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // ambil data guru untuk combo
    function getGuru() {
      return $this->db->query("select * from t002_guru order by idguru")->result();
    }

    // get all only in siswa
    function get_all_in_siswa()
    {
        // $this->db->order_by($this->id, $this->order);
        $s = "
          select
            a.idkelas,
            a.kelas
          from
            t003_kelas a
            left join t004_siswa b on a.idkelas = b.idkelas
          where
            b.tahunajaran = '".$this->session->userdata("tahunajaran")."'
          group by
            a.idkelas
        ";
        //$this->db->order_by($this->orderBy, $this->order);
        //return $this->db->get($this->table)->result();
        return $this->db->query($s)->result();
    }

}

/* End of file T003_kelas_model.php */
/* Location: ./application/models/T003_kelas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-19 06:41:35 */
/* http://harviacode.com */
