<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T103_nonrutin_model extends CI_Model
{

    public $table = 't103_nonrutin';
    public $id = 'idnonrutin';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_all() {
      //$this->db->order_by($this->id, $this->order);
      $this->db->order_by("idsiswa", "asc");
      $this->db->order_by("idjenis", "asc");
      $r = $this->db->get($this->table)->result();
      $aAll = array();
      $lewat = 1;
      foreach ($r as $row) {
        //$aAll[$row->idsiswa] = array($row->idjenis => $row->sisa);
        $aAll[$row->idsiswa][$row->idjenis] = $row->sisa;
      }
      return $aAll;
    }

    // get all
    function get_all_backup()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idnonrutin', $q);
	$this->db->or_like('idsiswa', $q);
	$this->db->or_like('nobayar', $q);
	$this->db->or_like('tglbayar', $q);
	$this->db->or_like('idjenis', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('bayar', $q);
	$this->db->or_like('sisa', $q);
	$this->db->or_like('idadmin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idnonrutin', $q);
	$this->db->or_like('idsiswa', $q);
	$this->db->or_like('nobayar', $q);
	$this->db->or_like('tglbayar', $q);
	$this->db->or_like('idjenis', $q);
	$this->db->or_like('nominal', $q);
	$this->db->or_like('bayar', $q);
	$this->db->or_like('sisa', $q);
	$this->db->or_like('idadmin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T103_nonrutin_model.php */
/* Location: ./application/models/T103_nonrutin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-29 01:40:20 */
/* http://harviacode.com */
